### ISSUE TITLE
Include all users in playlist rule

### ISSUE THREAD

**Issue by borFSU** [Maintainerr/Maintainerr#1058]
The 'Plex - Present in amount of playlists' rule only applies to the Plex owner account and not the managed users or Friends.  I would like to exclude titles that my users have included in their playlists from removal.  I can't seem to leverage the currently available rules to achieve this.  I have access to my managed users accounts, and I could duplicate the playlists on my account; however, I wouldn't be able to do this with Friends.

**Comment by lediszep** [comment]
I would like to see this too, would make a big difference

**Comment by jorenn92** [comment]
That could be challenging because playlists are tied to a user account. Unless they share the playlist with you, you won't be able to see it since we're logged in with the server owner account, not the specific user. There are other features like watchlists that pose similar challenges.

I'd like to explore alternative methods to fetch the data, possibly directly from the Plex database. However, I haven't had the time to investigate this yet.

**Comment by sadoMasupilami** [comment]
Could this be reopened? I search for a possibility to allow users to keep a film after they watch it. I am using pulsarr to tag films that are not on the watchlist anymore, so they have been watched. Sadly I don’t find a way to allow users to keep specific films even after they watched them
