### ISSUE TITLE
Hide Collection on Plex

### ISSUE THREAD

**Issue by WilliamsAve** [Maintainerr/Maintainerr#1059]
I've set my Movies library up to use the TMDB automatic collections.  It is configured to hide items which are in collections.  This gives me a nice looking movie browsing experience.

The issue I'm running into now is that when a movie gets added to the "leaving soon" collection by Maintainerr, it is no longer visible in the library, unless I go into the collection.  Is there a way to prevent that?

**Comment by ydkmlt84** [comment]
There is a setting inside of Plex that changes this. I don't remember exactly where but it's somewhere in the library settings.

**Comment by ohsnapword** [comment]
> There is a setting inside of Plex that changes this. I don't remember exactly where but it's somewhere in the library settings.

I've tried toying with the settings and can't get it to work.  For example, Back to the Future is in both the leaving soon collection and BttF collection.  The BttF collection is set to hide items but show collection and the leaving soon collection is set to show items.  In the main library view, the collection is shown as well as the movie because it is in both.  The show items setting is taking precedence.

**Comment by jorenn92** [comment]
Consider creating a manual collection and utilizing it in conjunction with your Maintainerr rule instead of relying on automatic collections, you could then configure this collection the way you need. 

However, ensure that you create a manual collection of the correct type (movies, shows, seasons, episodes). This is a common oversight that may prevent Maintainerr from adding items.

**Comment by ydkmlt84** [comment]
Closing as per #1071. There is a similar Feature Request here https://features.maintainerr.info/posts/11/option-to-not-sync-collection-with-plex .

Please discuss there, if needed.
