### ISSUE TITLE
Episodes not remove while flagged in PLex as seen

### ISSUE THREAD

**Issue by BarryV2021** [Maintainerr/Maintainerr#1114]
I have noticed that episodes that are being viewed by a different app (like Kodi) but are manually flagged in Plex as seen are not added to the collection for being deleted and are therefore not deleted.

**To Reproduce**
1. Go to Plex'
2. Click on an epsisode and manually flag the episode as being seen
3. Wait until add in the maintainerr collection wait until deleted. 

**Expected behavior**
Manually flagged episode deleted just like episode played and automatically flagged by Plex as beening seen.

**Device (please complete the following information):**
 - Qnap NAS
 - Maintainerr v2.0.3

**Comment by jorenn92** [comment]
This isn't a bug, but rather an intentional (and somewhat annoying) change made by Plex. Items manually marked as watched no longer generate 'play history' entries. For more information, you can refer to this forum post: [Plex View History Change in 1.40.0.x Server Version](https://forums.plex.tv/t/view-history-change-in-1-40-0-x-server-version/863316).

Unfortunately, there's nothing I can do to change this. Maintainer relies on play history, but we plan to introduce a Tautulli integration in the future. Once that's implemented, we should be able to fetch a more accurate watch history.

**Comment by BarryV2021** [comment]
Thanks jorenn92 for your answer. Until the Tautulli intergration I shall remove the few files manually.

Very happy with your work.
