### ISSUE TITLE
[WARN] [Error: Plex Server didnt respond with a valid 2xx status code, response code: 400] Couldn't add media to collection: 

### ISSUE THREAD

**Issue by modem7** [Maintainerr/Maintainerr#1218]
**Describe the bug**
[WARN] [Error: Plex Server didnt respond with a valid 2xx status code, response code: 400] Couldn't add media to collection: 

**To Reproduce**
Try to add content to collection manually

**Expected behavior**
For item to go into a collection

**Screenshots**
![image](https://github.com/user-attachments/assets/7ee18701-b062-4add-9430-c9bcae586ba1)

![image](https://github.com/user-attachments/assets/78000cb5-8a38-497c-9d73-02b9b15fcd6d)

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by modem7** [comment]
![image](https://github.com/user-attachments/assets/f937de83-9dd6-421b-bd17-b884be39acad)

**Comment by jorenn92** [comment]
Hey! Can you see the collection in Plex? If so, could you try manually removing it and then try again?

The most common cause of this error is a mismatch between media types when using a manual collection. For example, some users create 'show' type collections in Plex and then try to add seasons to them, which Plex doesn't allow. However, since you're not using a manual collection, this likely isn't the issue—unless there's an older collection with the same name and a different type still lingering in Plex.
