### ISSUE TITLE
Plex - [list] Viewed by (username) returning empty list

### ISSUE THREAD

**Issue by Bod1985** [Maintainerr/Maintainerr#1242]
**Describe the bug**
Episodes and Movies that have been watched do not reflect that when checking the viewed by list.

**To Reproduce**
1. Create a rule that uses the viewed by username list
2. Test a collection by finding known watched media
3. Observe empty list

Worth noting that "Total Views" accurately reflects the count such as 1 or 2.

**Expected behavior**
The list should contain a list of users that have viewed the content.

**Device (please complete the following information):**
 - OS: Debian
 - Version 12

**Comment by jorenn92** [comment]
Are the episodes actually watched? Or just marked as watched? Plex doesn’t generate watch records when you mark an item as watched.

**Comment by Bod1985** [comment]
> Are the episodes actually watched? Or just marked as watched? Plex doesn’t generate watch records when you mark an item as watched. 

I was testing with episodes I'd finished completely. I noticed it was working previously for weeks but now I've got lots of episodes left behind that my rule previously was deleting

**Comment by sameep22** [comment]
Just to add my two cents, I am also facing a similar issue. I know for a fact that I have seen a season, I can see the entries in Plex history and Tautulli, but on checking the media, Plex doesn't seem to return my username in the list of users that have seen the episodes.
Could this be related to the latest update?

**Comment by rickzim** [comment]
The same is happening to me. Movies and tv shows that were previously in the collection, are now being removed since my username is no longer in the list.

**Comment by appiekap653** [comment]
Same here, maintainerr 2.04 did work but since the last update something broke. 

Users that saw all available episodes returns empty 
Users that watch the show/season/episode returns also empty

**Comment by jorenn92** [comment]
Are you testing this with the server owner by any chance? I’ve tracked the issue down to how Plex manages the owner's account ID. For some reason, the owner’s ID is set to '1' instead of their actual Plex ID. In version 2.1.0, I refactored the code to fetch information from Plex's community API to provide more accurate details for users, including the owner’s correct ID. However, this caused issues because the watchlist still uses '1' for the owner. I’ve now refactored the code again to account for this. After https://github.com/jorenn92/Maintainerr/pull/1252 is merged, it should work as expected.

**Comment by zenxedo** [comment]
I am still having this issue for the main user using 2.1.1

**Comment by rickzim** [comment]
> I am still having this issue for the main user using 2.1.1

For me the issue remains on movies as well. But it seems to be fixed for TV Shows.

**Comment by jorenn92** [comment]
@zenxedo @rickzim, my bad—I may have overlooked the 'Viewed by' rule for movies and only applied the fix for shows. This should now be resolved for movies as well after the merge of [this PR](https://github.com/jorenn92/Maintainerr/pull/1266).

Would you be able to verify this using the main/develop image?

**Comment by rickzim** [comment]
@jorenn92 Np! Thank you for being on it so quickly. Im currently unable to test it but i'll ask a friend!

**Comment by zenxedo** [comment]
Thank you for the fast fix and a great app. Tested in develop and it's working now
