### ISSUE TITLE
[Feature Request] Compatible with Jellyfin

### ISSUE THREAD

**Issue by xiNeRoar** [Maintainerr/Maintainerr#456]
hope this useful repo can extend its support to jellyfin which is also a very popular project

**Comment by jorenn92** [comment]
Hey, I first want to focus on the core functionality. After that, I'll focus on adding more services and rules. Jellyfin, which is indeed a popular media server, will definitely be one of the first services to be added.

**Comment by LaSylv** [comment]
Would you accept PRs for jellyfin support ?

If so, do you have an id of how to implement it ?

**Comment by jorenn92** [comment]
I would be willing to support this idea if it is executed correctly. As of now, I haven't thoroughly considered all aspects, but the primary challenge lies in Maintainerr's strong reliance on Plex.

To address this, my initial thought is to introduce a wrapper class designed to encompass all essential functionalities. This class would serve as a drop in substitute for the current Plex service. The key modification involves this service retrieving actual data from the configured media server.

However, Maintainerr directly interacts with Plex API responses. Therefore, integrating Jellyfin as an alternative would necessitate translating Jellyfin's responses into the Plex format. I haven't delved into the specifics of Jellyfin's API, but I anticipate that this translation process might be a substantial amount of work.

**Comment by Schaka** [comment]
Why the dependence on Plex?
I get that you're working with collections (and I love the idea), but you can still do cleanup via Sonarr/Radarr.
As long as you clean up the requests in Overseerr/Jellyseerr so that your users can re-request things if they do end up wanting to watch it after all, it should be fine.

I had been looking at doing a cleanup tool myself. Sonarr/Radarr already provide a history for each item of media. 
I guess you get viewing data directly from Plex and that's why it's so tightly integrated?

**Comment by jorenn92** [comment]
> Why the dependence on Plex? I get that you're working with collections (and I love the idea), but you can still do cleanup via Sonarr/Radarr. As long as you clean up the requests in Overseerr/Jellyseerr so that your users can re-request things if they do end up wanting to watch it after all, it should be fine.
> 
> I had been looking at doing a cleanup tool myself. Sonarr/Radarr already provide a history for each item of media. I guess you get viewing data directly from Plex and that's why it's so tightly integrated?

Plex data is essentially the foundation for almost all operations. If a media item isn't present in your Plex library, Maintainerr won't detect it. 

Originally, Maintainerr was just a private personal project, I wasn't initially focused on its adaptability to other media servers.

While it's not impossible to alter this behavior, it would require a some effort. I'd be supportive if someone comes along that would like to give it a shot.

**Comment by Schaka** [comment]
That makes perfect sense. I think multi server support (and Jellyseerr on top of Overseerr) is a huge undertaking.
I definitely think I'm better off just handling my (much smaller) use case myself. 

The idea is great though, so if I end up ever publishing anything, I'll credit you.

**Comment by jorenn92** [comment]
> As promised, I've worked on my own application. It doesn't come with a GUI and does not have feature parity with Maintainerr, nor will it likely ever get to that point due to restrictions in the Jellyfin API.
> 
> But for anyone looking for Maintainerr with Jellyfin support who thinks having some sort of cleanup tool is better than none, I present [Janitorr](https://github.com/Schaka/janitorr)

Funny side note, i once wanted to rename Maintainerr to Janitorr, but it was to much of a hassle.

just out of curiosity, what kind of Jellyfin API restrictions did you meet?

**Comment by Schaka** [comment]
They don't really let you create collections of already existing media freely.

I've considered creating a collection (they mostly build them around box sets, so meta data becomes an issue), but then you can't choose to put it on the front page as far as I can tell. So it's hidden to most users.

I've tried creating a library for TV shows and manually assigning every season's folder. Jellyfin then just won't pick up on any media. It needs to be pointed towards one folder where it can find TV shows with season folders.

There may be ways around it, but I tried different ways for 3 days straight. I'm now thinking of creating a copy of the folder structure and maintain a tree of hard links, because I really like the idea of that feature.

If there's another (better) way to manage it, I'd love that.

There's also no stats in jellyfin and I don't want to depend on a scarcely maintained plug-in which people would have to install and couldn't delete media for which no stats exist.

**Comment by jorenn92** [comment]
I see, that would make adding support for it in Maintainerr quite difficult as well. Thanks for the references in your readme btw!
