### ISSUE TITLE
[Feature request] Exclude existing collections

### ISSUE THREAD

**Issue by utlilb** [Maintainerr/Maintainerr#493]
**Is your feature request related to a problem? Please describe.**
Don't want to remove media that is part of existing collection, regardless of watch status.

**Describe the solution you'd like**
A rule to mass exclude existing collections.

**Comment by jorenn92** [comment]
Thanks for the suggestion.

i believe 2 rules might be useful: 
- Plex - Present in amount of collections (number)
- Plex -  Collection names media is present in(text list)

**Comment by ydkmlt84** [comment]
I just took a look but I only see the "Present in amount of collections (number)" when the Library and media type is set to TV and Show. I didn't see it anywhere else.

**Comment by jorenn92** [comment]
I meant that those 2 might be useful additions. I’m not entirely sure why “Present in amount of collections” is only available with tv shows. I’ll look into this.

**Comment by jorenn92** [comment]
The reason for 'Present in amount of collections' to be absent from movies was actually due to a logic error in the UI code since the addition of seasons & episodes.

I refactored the code a bit. It will now return the amount of collections an item is present in, excluding the rule's own collection. It'll be available for all media types now. 

I also added a rule value that returns a list of all the collection names an item is present in (for instance, for exclusions of specific collections)

This will be available in the next release.
