### ISSUE TITLE
[FEATURE] Add Plex rating to criteria to exclude favorite movies

### ISSUE THREAD

**Issue by niyazaki** [Maintainerr/Maintainerr#680]
First of all, thank you for your work.
**Is your feature request related to a problem? Please describe.**
I haven't set any rules yet because of the fact that I'm afraid of loosing my favorites movies that I watch multiple time with my friends. I would love to be able to exclude those titles from the auto delete rules based on their ratings on Plex. I can also imagine rules for really bad movies that my users who doesn't have the right to delete movies have seen and doesn't want others to loose time on this specific movie.

**Describe the solution you'd like**
I would like to be able to have rules based on the rating from a specific user. If someones puts a 5* the movie should never be deleted and if someone puts 1* on a movie it should be deleted after a quicker time than default period (except if someone else puts a 5* on the movie).

**Describe alternatives you've considered**
Exception list inside the app but I don't want my user to access Maintenerr so I will have to do it manualy (who's the first purpose of creating this app)

**Comment by jorenn92** [comment]
Hey, sorry for my late reply.

The rating rules are expanded in #705 & #709. These are currently available in develop and will be part of the next release.

**Comment by niyazaki** [comment]
Hey Joren, no wories. Thank you for the answer. Would love to give you a hand on this app when I got time as I think this is a great project.

PS : That's the first time I see a docker compose mentionning Brussels. It made me smile 😄

**Comment by jorenn92** [comment]
No problem. You're welcome to help; I could definitely use it!

And haha, well, it doesn't always have to be New York. 😀

**Comment by niyazaki** [comment]
Hi @jorenn92 sorry to bother you again. I've looked into  #705 and #709. I've also looked into some related topics like #703 but I'm still in trouble.

I added the community rule "Seen by Overseer requester & older than 30 days OR not watched by requester and older than 90 days" and updated it by adding a "AND" rule: Plex - User rating, smaller, number, 4.
But I can't get it to work. To give you more context: I have 2 profiles on my account, me, the admin and a managed plex profile.

The value is only taken for the admin profile, the managed one isn't preventing the deletes.
Also, all the user I share my library with have no impact.

That doesn't fit my needs. So, as a workaround I tried to use "Plex - Last view date". My idea was: if someone plays a movie, remove it from the auto-delete collection for a couple days to give them more time. But this doesn't seem to work either for other user (nor mine to be honnest).
And finaly, I tried another workaround with "Plex - Times viewed" in order to avoid deleting my classic movies that I watch on a regular basis, but this didn't work either.

Do you have any recommandation for me ? I'm open to do some dev if you can give me some doc or knowledge transfer to have those features.

Your Belgian Friend.

**Comment by jorenn92** [comment]
Hi there! I was initially concerned that the user limitation with ratings might be present, as I don't personally use ratings and haven't thoroughly tested this aspect.

Perhaps a more suitable endpoint exists, potentially from plex.tv instead of your local server. However, Plex's API endpoints are undocumented, making it challenging to find an alternative solution.

Could you explain why the 'Plex - Last view date' feature isn't working for you? This function should retrieve the last viewing date from Plex's watch history, it should work unless there's a reason specific to your account (such as a recent server reinstallation).

Please feel free to submit a pull request if you're able to enhance the rating or other behavior! Regrettably, the online API documentation is limited and incomplete. My approach has been to monitor the calls Plex Web creates to determine available data,
