### ISSUE TITLE
[Feature Request ]Add *arr root folder or Plex media directory as a rule

### ISSUE THREAD

**Issue by neotoxicfr** [Maintainerr/Maintainerr#756]
**Is your feature request related to a problem? Please describe.**
Not a bug, I'd prefer not to create collections as I do them by-hand and not for managing purpose.

**Describe the solution you'd like**
Having the possibility to execute rules based on the root folder of a media, as I have these ones :
- Movies
- Movies temp
- Shows Shows temp
- Animes
- Animes temp
I only have 3 libraries in Plex to make it easier for everyone to see them, each one having both temp and non temp as it's only for managing purposes, default overseerr requests being temp, I switch them myself if I judge it "worthy of keeping".

**Describe alternatives you've considered**
None really.

**Additional context**
No idea atm.

**Comment by jorenn92** [comment]
Hello, I'd appreciate some clarification on your feedback regarding the report. If I understand correctly, you prefer that Maintainerr does not generate collections in Plex. Unfortunately, turning off this feature is not possible since it constitutes a fundamental aspect of the tool's functionality. However, you do have the option to disable the "show on home" feature or manually create your own collection, specifying it in Maintainerr.

It's essential to note that Maintainerr solely communicates with the Plex API to retrieve media and is indifferent to the storage location. The Plex API response doesn't include a directory path. While Arr does provide a directory path, it's worth mentioning that in a dockerized environment, the path will be within the container.

If you're utilizing docker, the directory path may not be particularly useful unless you're interested in conducting checks for partial matches. If this is the case, please let me know your specific requirements or any adjustments you'd like, and I'll do my best to accommodate.

**Comment by neoestremi** [comment]
Thank you for these clarifications, if the collection can be hidden, that's a big plus.
The thing is, in the current state, I have to manually add every movie that I want to be checked manually because if I let maintainerr do it, it will grab movies I want to keep, and again I would have to exclude them, so one way or the other, I have to manually choose which ones will be kept or deleted.
If I could add a rule which only grabbed medias located in a specific folder with an *arr root directory with, say, matches a string or contain certain words, that would be a big plus.

**Comment by jorenn92** [comment]
I could include a rule for the *arr media location, but as i mentioned this would be the path inside the container. However, if this aligns with your use case or proves useful in your specific scenario, i'll add it.

**Comment by neoestremi** [comment]
I'm pretty sure it is the only way to use maintainerr without having to filter everything by-hand, so if you can do it, I will gladly try it once it's out to let you know it works 💯

**Comment by ydkmlt84** [comment]
I thought of a way to possibly do this with the way everything is currently. In Radarr or Sonarr you can create a filter based off of the path. Then easily add a tag to all of the media from that filter. Then use that tag in Maintainerr.

**Comment by neoestremi** [comment]
> I thought of a way to possibly do this with the way everything is currently. In Radarr or Sonarr you can create a filter based off of the path. Then easily add a tag to all of the media from that filter. Then use that tag in Maintainerr.

Thanks, I added the tag to all existing medias for temp directories, added the tag in overseerr (everything is automatically accepted as temp) so when I want something to be switched to "non temp" I juste have to remove the tag too, not very time consuming, I'm now trying to tweak the rules.
As I understand, the medias will be effectively removed after being in the collection for the number of days set in the rule, even though the rules said, date added before last 30 days right ?

**Comment by jorenn92** [comment]
PR #814 introduces two new rules:

- A Radarr rule that retrieves the file path along with the file name set in Radarr.
- A Sonarr rule that returns the base path for the media items, excluding filenames.

Please note that these paths are relative to the container environment.

**Comment by neoestremi** [comment]
New rule works perfectly, can revert my tags :) thank you very much, and nice update btw, still tweaking for sonarr.
